// pipeline must be top-level

pipeline {
    agent any

    parameters {
        choice(name: 'VERSION', choices: ['1.1.1', '1.1.2', '1.1.3'], description: 'verstion to dpeloy on prod')
        booleanParam(name: 'executeTests', defaultValue: true, description: '')
    }

    stages {
        stage("build") {
            steps {
                echo "building the application"
            }
        }

        stage("test") {
            when {
                // use parameters
                expression {
                    params.executeTests == true
                }
            }
            steps {
                echo "testing the application"
            }
        }

        stage("deploy") {
            steps {
                echo "deploying version ${params.VERSION}"
            }
        }
    }
}